server:
  port: 8088

spring:
  application:
    name: application
  profiles:
    active: dev,db

ftpConfig:
  host: 192.168.0.109
  port: 22
  username: jack
  password: ******
  marketQuoteSrc: /home/jack/tmp/market_quote.csv
  marketQuoteDst: e://market_quote/market_quote.csv